import type { DestinationMetadata } from "./index"

export const GOLD_MARKER = "#D4AF37"

export const DESTINATION_REGION_BY_ID: Record<string, string> = {
  japan: 'Asia',
  switzerland: 'Europe',
  france: 'Europe',
  italy: 'Europe',
  germany: 'Europe',
  'united-arab-emirates': 'Middle East',
  maldives: 'Indian Ocean',
  singapore: 'Asia',
  greece: 'Europe',
  australia: 'Oceania',
  'new-zealand': 'Oceania',
  norway: 'Europe',
  iceland: 'Europe',
  canada: 'North America',
  'united-kingdom': 'Europe',
  spain: 'Europe',
  turkiye: 'Europe & Asia',
  austria: 'Europe',
  portugal: 'Europe',
  netherlands: 'Europe',
  ireland: 'Europe',
  belgium: 'Europe',
  denmark: 'Europe',
  sweden: 'Europe',
  'czech-republic': 'Europe',
  hungary: 'Europe',
  china: 'Asia',
  thailand: 'Asia',
  malaysia: 'Asia',
  'south-korea': 'Asia',
  vietnam: 'Asia',
  indonesia: 'Asia',
  philippines: 'Asia',
  'hong-kong': 'Asia',
  'united-states': 'North America',
  mexico: 'North America',
  egypt: 'Africa',
  'south-africa': 'Africa',
  brazil: 'South America',
  argentina: 'South America',
  india: 'Asia',
  'sri-lanka': 'Asia',
  nepal: 'Asia',
  bhutan: 'Asia',
  cambodia: 'Asia',
  taiwan: 'Asia',
  uzbekistan: 'Central Asia',
  georgia: 'Europe & Asia',
  finland: 'Europe',
  croatia: 'Europe',
  poland: 'Europe',
  morocco: 'Africa',
  kenya: 'Africa',
  tanzania: 'Africa',
  namibia: 'Africa',
  seychelles: 'Indian Ocean',
  mauritius: 'Indian Ocean',
  oman: 'Middle East',
  qatar: 'Middle East',
  peru: 'South America',
  chile: 'South America',
  ecuador: 'South America',
  'costa-rica': 'Central America',
  fiji: 'Oceania',
  'french-polynesia': 'Oceania',
  'saudi-arabia': 'Middle East',
}

export const getDestinationRegion = (id: string) =>
  DESTINATION_REGION_BY_ID[id] ?? 'Worldwide'

export const destinationMetadata: DestinationMetadata[] = [
  {
    id: "japan",
    name: "Japan",
    latitude: 36.2048,
    longitude: 138.2529,
    zoom: 1.34,
    markerColor: GOLD_MARKER,
    flag: "🇯🇵",
    tagline: "Where timeless traditions meet unforgettable experiences.",
    image: "/images/destinations/japan/japan-mount-fuji-sunrise.webp",
    bestSeason: "Mar–May · Oct–Nov",
  },
  {
    id: "switzerland",
    name: "Switzerland",
    latitude: 46.8182,
    longitude: 8.2275,
    zoom: 1.4,
    markerColor: GOLD_MARKER,
    flag: "🇨🇭",
    tagline: "Where every journey rises above the ordinary.",
    image:
    "https://images.unsplash.com/photo-1527668752968-14dc70a27c95?q=85&w=2000&auto=format&fit=crop",
    bestSeason: "May–Sep · Dec–Mar",
  },
  {
    id: "france",
    name: "France",
    latitude: 46.2276,
    longitude: 2.2137,
    zoom: 1.34,
    markerColor: GOLD_MARKER,
    flag: "🇫🇷",
    tagline: "Where culture becomes a way of life.",
    image:
    "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=85&w=2000&auto=format&fit=crop",
    bestSeason: "Apr–Jun · Sep–Oct",
  },
  {
    id: "italy",
    name: "Italy",
    latitude: 42.8333,
    longitude: 12.8333,
    zoom: 1.34,
    markerColor: GOLD_MARKER,
    flag: "🇮🇹",
    tagline: "Where beauty is not preserved—it is lived.",
    image: "/images/destinations/italy/italy-amalfi-coast-optimized.webp",
    bestSeason: "Apr–Jun · Sep–Oct",
  },
  {
    id: "germany",
    name: "Germany",
    latitude: 51.1657,
    longitude: 10.4515,
    zoom: 1.34,
    markerColor: GOLD_MARKER,
    flag: "🇩🇪",
    tagline: "Where history and imagination meet.",
    image:
    "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?q=85&w=2000&auto=format&fit=crop",
    bestSeason: "May–Sep · Nov–Dec",
  },
  {
    id: "united-arab-emirates",
    name: "United Arab Emirates",
    latitude: 24.2075,
    longitude: 55.7447,
    zoom: 1.42,
    markerColor: GOLD_MARKER,
    flag: "🇦🇪",
    tagline: "Where ambition rises from the desert.",
    image:
    "/images/destinations/uae/dubai.webp",
    bestSeason: "Nov–Mar",
  },
  {
    id: "maldives",
    name: "Maldives",
    latitude: 3.2028,
    longitude: 73.2207,
    zoom: 1.5,
    markerColor: GOLD_MARKER,
    flag: "🇲🇻",
    tagline: "Where the ocean becomes your world.",
    image:
    "/images/services/accommodation/maldives-overwater-villa.jpg",
    bestSeason: "Nov–Apr",
  },
  {
    id: "singapore",
    name: "Singapore",
    latitude: 1.3521,
    longitude: 103.8198,
    zoom: 1.46,
    markerColor: GOLD_MARKER,
    flag: "🇸🇬",
    tagline: "Where the world meets in one city.",
    image:
    "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?q=85&w=2000&auto=format&fit=crop",
    bestSeason: "Feb–Apr · Jul–Sep",
  },
  {
    id: "greece",
    name: "Greece",
    latitude: 39.0742,
    longitude: 21.8243,
    zoom: 1.38,
    markerColor: GOLD_MARKER,
    flag: "🇬🇷",
    tagline: "Where legends meet the Aegean.",
    image: "/images/destinations/greece/greece-mykonos-street.webp",
    bestSeason: "Apr–Jun · Sep–Oct",
  },
  {
    id: "australia",
    name: "Australia",
    latitude: -25.2744,
    longitude: 133.7751,
    zoom: 1.25,
    markerColor: GOLD_MARKER,
    flag: "🇦🇺",
    tagline: "Where the wild becomes extraordinary.",
    image: "/images/destinations/australia/australia.webp",
    bestSeason: "Sep–Nov · Mar–May",
  },
  {
    id: "new-zealand",
    name: "New Zealand",
    latitude: -41.2,
    longitude: 174.0,
    zoom: 1.34,
    markerColor: GOLD_MARKER,
    flag: "🇳🇿",
    tagline: "Where every landscape tells a story.",
    image:
    "https://images.unsplash.com/photo-1469521669194-babb45599def?q=85&w=2000&auto=format&fit=crop",
    bestSeason: "Nov–Apr",
  },
  {
    id: "norway",
    name: "Norway",
    latitude: 61.5,
    longitude: 9.0,
    zoom: 1.36,
    markerColor: GOLD_MARKER,
    flag: "🇳🇴",
    tagline: "Where the mountains meet the Arctic sea.",
    image: "/images/destinations/europe/norway.webp",
    bestSeason: "May–Sep · Sep–Mar",
  },
  {
    id: "iceland",
    name: "Iceland",
    latitude: 64.9631,
    longitude: -19.0208,
    zoom: 1.34,
    markerColor: GOLD_MARKER,
    flag: "🇮🇸",
    tagline: "Where the Earth reveals its power.",
    image: "/images/destinations/europe/iceland.webp",
    bestSeason: "Jun–Aug · Sep–Mar",
  },
  {
    id: "canada",
    name: "Canada",
    latitude: 56.1304,
    longitude: -106.3468,
    zoom: 1.22,
    markerColor: GOLD_MARKER,
    flag: "🇨🇦",
    tagline: "Where wilderness knows no limits.",
    image: "/images/destinations/canada/canada-moraine-lake.webp",
    bestSeason: "May–Sep · Dec–Mar",
  },
  {
    id: "united-kingdom",
    name: "United Kingdom",
    latitude: 54.0,
    longitude: -2.0,
    zoom: 1.34,
    markerColor: GOLD_MARKER,
    flag: "🇬🇧",
    tagline: "Where history shapes every landscape.",
    image: "/images/destinations/europe/united-kingdom.webp",
    bestSeason: "May–Sep",
  },
  {
    id: "spain",
    name: "Spain",
    latitude: 40.4637,
    longitude: -3.7492,
    zoom: 1.34,
    markerColor: GOLD_MARKER,
    flag: "🇪🇸",
    tagline: "Where every region reveals a different soul.",
    image: "/images/destinations/europe/spain.webp",
    bestSeason: "Apr–Jun · Sep–Oct",
  },
  {
    id: "turkiye",
    name: "Türkiye",
    latitude: 38.9637,
    longitude: 35.2433,
    zoom: 1.34,
    markerColor: GOLD_MARKER,
    flag: "🇹🇷",
    tagline: "Where continents and civilisations converge.",
    image: "/images/destinations/turkiye/turkey.webp",
    bestSeason: "Apr–Jun · Sep–Oct",
  },
  {
    id: "austria",
    name: "Austria",
    latitude: 47.5162,
    longitude: 14.5501,
    zoom: 1.38,
    markerColor: GOLD_MARKER,
    flag: "🇦🇹",
    tagline: "Where imperial culture meets the Alps.",
    image: "/images/destinations/europe/austria.webp",
    bestSeason: "May–Sep · Dec–Mar",
  },
  {
    id: "portugal",
    name: "Portugal",
    latitude: 39.3999,
    longitude: -8.2245,
    zoom: 1.38,
    markerColor: GOLD_MARKER,
    flag: "🇵🇹",
    tagline: "Where the Atlantic shapes the soul.",
    image: "/images/destinations/europe/portugal.webp",
    bestSeason: "Apr–Jun · Sep–Oct",
  },
  {
    id: "netherlands",
    name: "Netherlands",
    latitude: 52.1326,
    longitude: 5.2913,
    zoom: 1.4,
    markerColor: GOLD_MARKER,
    flag: "🇳🇱",
    tagline: "Where water, art and design converge.",
    image: "/images/destinations/europe/netherlands.webp",
    bestSeason: "Apr–Sep",
  },
  {
    id: "ireland",
    name: "Ireland",
    latitude: 53.1424,
    longitude: -7.6921,
    zoom: 1.4,
    markerColor: GOLD_MARKER,
    flag: "🇮🇪",
    tagline: "Where stories live within the landscape.",
    image: "/images/destinations/europe/ireland.webp",
    bestSeason: "May–Sep",
  },
  {
    id: "belgium",
    name: "Belgium",
    latitude: 50.5039,
    longitude: 4.4699,
    zoom: 1.42,
    markerColor: GOLD_MARKER,
    flag: "🇧🇪",
    tagline: "Where artistry and craftsmanship endure.",
    image: "/images/destinations/europe/belgium.webp",
    bestSeason: "Apr–Sep",
  },
  {
    id: "denmark",
    name: "Denmark",
    latitude: 56.2639,
    longitude: 9.5018,
    zoom: 1.42,
    markerColor: GOLD_MARKER,
    flag: "🇩🇰",
    tagline: "Where simplicity becomes an art form.",
    image: "/images/destinations/europe/denmark.webp",
    bestSeason: "May–Sep",
  },
  {
    id: "sweden",
    name: "Sweden",
    latitude: 62.0,
    longitude: 15.0,
    zoom: 1.38,
    markerColor: GOLD_MARKER,
    flag: "🇸🇪",
    tagline: "Where nature and design exist in harmony.",
    image: "/images/destinations/europe/sweden.webp",
    bestSeason: "May–Sep · Dec–Mar",
  },
  {
    id: "czech-republic",
    name: "Czech Republic",
    latitude: 49.8175,
    longitude: 15.473,
    zoom: 1.42,
    markerColor: GOLD_MARKER,
    flag: "🇨🇿",
    tagline: "Where centuries of artistry shape every city.",
    image: "/images/destinations/europe/czech-republic.webp",
    bestSeason: "Apr–Jun · Sep–Oct",
  },
  {
    id: "hungary",
    name: "Hungary",
    latitude: 47.1625,
    longitude: 19.5033,
    zoom: 1.42,
    markerColor: GOLD_MARKER,
    flag: "🇭🇺",
    tagline: "Where the Danube carries centuries of culture.",
    image: "/images/destinations/europe/hungary.webp",
    bestSeason: "Apr–Jun · Sep–Oct",
  },
  {
    id: "china",
    name: "China",
    latitude: 35.8617,
    longitude: 104.1954,
    zoom: 1.28,
    markerColor: GOLD_MARKER,
    flag: "🇨🇳",
    tagline: "Where civilisation unfolds on a monumental scale.",
    image: "/images/destinations/asia/china.webp",
    bestSeason: "Apr–May · Sep–Oct",
  },
  {
    id: "thailand",
    name: "Thailand",
    latitude: 15.87,
    longitude: 100.9925,
    zoom: 1.36,
    markerColor: GOLD_MARKER,
    flag: "🇹🇭",
    tagline: "Where grace is woven into everyday life.",
    image: "/images/destinations/asia/thailand.webp",
    bestSeason: "Nov–Feb",
  },
  {
    id: "malaysia",
    name: "Malaysia",
    latitude: 4.2105,
    longitude: 101.9758,
    zoom: 1.4,
    markerColor: GOLD_MARKER,
    flag: "🇲🇾",
    tagline: "Where cultures, rainforests and seas converge.",
    image: "/images/destinations/asia/malaysia.webp",
    bestSeason: "Mar–Sep · varies by coast",
  },
  {
    id: "south-korea",
    name: "South Korea",
    latitude: 35.9078,
    longitude: 127.7669,
    zoom: 1.38,
    markerColor: GOLD_MARKER,
    flag: "🇰🇷",
    tagline: "Where ancient restraint meets modern imagination.",
    image: "/images/destinations/asia/south-korea.webp",
    bestSeason: "Apr–Jun · Sep–Nov",
  },
  {
    id: "vietnam",
    name: "Vietnam",
    latitude: 14.0583,
    longitude: 108.2772,
    zoom: 1.38,
    markerColor: GOLD_MARKER,
    flag: "🇻🇳",
    tagline: "Where history flows through landscape and flavour.",
    image: "/images/destinations/vietnam/vietnam-ha-long-bay.webp",
    bestSeason: "Feb–Apr · Sep–Nov",
  },
  {
    id: "indonesia",
    name: "Indonesia",
    latitude: -2.5489,
    longitude: 118.0149,
    zoom: 1.32,
    markerColor: GOLD_MARKER,
    flag: "🇮🇩",
    tagline: "Where thousands of islands tell one extraordinary story.",
    image: "/images/destinations/asia/indonesia.webp",
    bestSeason: "Apr–Oct",
  },
  {
    id: "philippines",
    name: "Philippines",
    latitude: 12.8797,
    longitude: 121.774,
    zoom: 1.38,
    markerColor: GOLD_MARKER,
    flag: "🇵🇭",
    tagline: "Where island worlds unfold beyond the horizon.",
    image: "/images/destinations/asia/philippines.webp",
    bestSeason: "Dec–May",
  },
  {
    id: "hong-kong",
    name: "Hong Kong",
    latitude: 22.3193,
    longitude: 114.1694,
    zoom: 1.5,
    markerColor: GOLD_MARKER,
    flag: "🇭🇰",
    tagline: "Where harbour, mountain and metropolis converge.",
    image: "/images/destinations/asia/hong-kong.webp",
    bestSeason: "Oct–Dec · Mar–Apr",
  },
  {
    id: "united-states",
    name: "United States",
    latitude: 39.8283,
    longitude: -98.5795,
    zoom: 1.1,
    markerColor: GOLD_MARKER,
    flag: "🇺🇸",
    tagline: "A continent of landscapes, cultures and reinvention.",
    image: "/images/destinations/americas/united-states.webp",
    bestSeason: "Apr–Jun · Sep–Oct",
  },
  {
    id: "mexico",
    name: "Mexico",
    latitude: 23.6345,
    longitude: -102.5528,
    zoom: 1.3,
    markerColor: GOLD_MARKER,
    flag: "🇲🇽",
    tagline: "Land of Sun and Soul",
    image: "/images/destinations/americas/mexico.webp",
    bestSeason: "Nov–Apr",
  },
  {
    id: "egypt",
    name: "Egypt",
    latitude: 26.8206,
    longitude: 30.8025,
    zoom: 1.32,
    markerColor: GOLD_MARKER,
    flag: "🇪🇬",
    tagline: "Where civilisation rises from the Nile.",
    image: "/images/destinations/africa/egypt.webp",
    bestSeason: "Oct–Apr",
  },
  {
    id: "south-africa",
    name: "South Africa",
    latitude: -30.5595,
    longitude: 22.9375,
    zoom: 1.3,
    markerColor: GOLD_MARKER,
    flag: "🇿🇦",
    tagline: "Where wilderness, culture and coast meet.",
    image: "/images/destinations/africa/south-africa.webp",
    bestSeason: "Mar–May · Sep–Nov",
  },
  {
    id: "brazil",
    name: "Brazil",
    latitude: -14.235,
    longitude: -51.9253,
    zoom: 1.26,
    markerColor: GOLD_MARKER,
    flag: "🇧🇷",
    tagline: "Where nature moves to its own rhythm.",
    image: "/images/destinations/americas/brazil.webp",
    bestSeason: "May–Sep",
  },
  {
    id: "argentina",
    name: "Argentina",
    latitude: -38.4161,
    longitude: -63.6167,
    zoom: 1.28,
    markerColor: GOLD_MARKER,
    flag: "🇦🇷",
    tagline: "A country of elemental landscapes and enduring passion.",
    image: "/images/destinations/americas/argentina.webp",
    bestSeason: "Oct–Apr",
  },
  {
    id: "sri-lanka",
    name: "Sri Lanka",
    latitude: 7.8731,
    longitude: 80.7718,
    zoom: 1.42,
    markerColor: GOLD_MARKER,
    flag: "🇱🇰",
    tagline: "An island shaped by monsoon, memory and sea.",
    image: "/images/destinations/asia/sri-lanka.webp",
    bestSeason: "Dec–Mar · Jul–Sep",
  },
  {
    id: "nepal",
    name: "Nepal",
    latitude: 28.3949,
    longitude: 84.124,
    zoom: 1.42,
    markerColor: GOLD_MARKER,
    flag: "🇳🇵",
    tagline: "Where sacred valleys rise into the Himalaya.",
    image: "/images/destinations/asia/nepal.webp",
    bestSeason: "Oct–Nov · Mar–Apr",
  },
  {
    id: "bhutan",
    name: "Bhutan",
    latitude: 27.5142,
    longitude: 90.4336,
    zoom: 1.44,
    markerColor: GOLD_MARKER,
    flag: "🇧🇹",
    tagline: "Where happiness is measured beyond prosperity.",
    image: "/images/destinations/bhutan/bhutan-tigers-nest.webp",
    bestSeason: "Mar–May · Sep–Nov",
  },
  {
    id: "cambodia",
    name: "Cambodia",
    latitude: 12.5657,
    longitude: 104.991,
    zoom: 1.42,
    markerColor: GOLD_MARKER,
    flag: "🇰🇭",
    tagline: "Where the Khmer world still lives.",
    image: "/images/destinations/asia/cambodia.webp",
    bestSeason: "Nov–Feb",
  },
  {
    id: "taiwan",
    name: "Taiwan",
    latitude: 23.6978,
    longitude: 120.9605,
    zoom: 1.45,
    markerColor: GOLD_MARKER,
    flag: "🇹🇼",
    tagline: "Where ancient traditions meet tomorrow's skyline.",
    image: "/images/destinations/asia/taiwan.webp",
    bestSeason: "Oct–Apr",
  },
  {
    id: "uzbekistan",
    name: "Uzbekistan",
    latitude: 41.3775,
    longitude: 64.5853,
    zoom: 1.4,
    markerColor: GOLD_MARKER,
    flag: "🇺🇿",
    tagline: "Where the Silk Road still glows in blue.",
    image: "/images/destinations/asia/uzbekistan.webp",
    bestSeason: "Apr–May · Sep–Oct",
  },
  {
    id: "georgia",
    name: "Georgia",
    latitude: 42.3154,
    longitude: 43.3569,
    zoom: 1.4,
    markerColor: GOLD_MARKER,
    flag: "🇬🇪",
    tagline: "Where Europe meets the Caucasus.",
    image: "/images/destinations/asia/georgia.webp",
    bestSeason: "May–Jun · Sep–Oct",
  },
  {
    id: "finland",
    name: "Finland",
    latitude: 61.9241,
    longitude: 25.7482,
    zoom: 1.38,
    markerColor: GOLD_MARKER,
    flag: "🇫🇮",
    tagline: "Where nature becomes a way of life.",
    image: "/images/destinations/europe/finland.webp",
    bestSeason: "Jun–Aug · Dec–Mar",
  },
  {
    id: "croatia",
    name: "Croatia",
    latitude: 45.1,
    longitude: 15.2,
    zoom: 1.4,
    markerColor: GOLD_MARKER,
    flag: "🇭🇷",
    tagline: "Where the Adriatic holds centuries of stories.",
    image: "/images/destinations/europe/croatia.webp",
    bestSeason: "May–Jun · Sep",
  },
  {
    id: "poland",
    name: "Poland",
    latitude: 51.9194,
    longitude: 19.1451,
    zoom: 1.38,
    markerColor: GOLD_MARKER,
    flag: "🇵🇱",
    tagline: "Where resilience shaped a remarkable nation.",
    image: "/images/destinations/europe/poland.webp",
    bestSeason: "May–Sep",
  },
  {
    id: "morocco",
    name: "Morocco",
    latitude: 31.7917,
    longitude: -7.0926,
    zoom: 1.34,
    markerColor: GOLD_MARKER,
    flag: "🇲🇦",
    tagline: "Where every doorway opens into another world.",
    image: "/images/destinations/africa/morocco.webp",
    bestSeason: "Mar–May · Sep–Nov",
  },
  {
    id: "kenya",
    name: "Kenya",
    latitude: -0.0236,
    longitude: 37.9062,
    zoom: 1.32,
    markerColor: GOLD_MARKER,
    flag: "🇰🇪",
    tagline: "Where the wilderness still moves to an ancient rhythm.",
    image: "/images/destinations/africa/kenya.webp",
    bestSeason: "Jan–Feb · Jun–Oct",
  },
  {
    id: "tanzania",
    name: "Tanzania",
    latitude: -6.369,
    longitude: 34.8888,
    zoom: 1.32,
    markerColor: GOLD_MARKER,
    flag: "🇹🇿",
    tagline: "Soul of the Serengeti",
    image: "/images/destinations/africa/tanzania.webp",
    bestSeason: "Jun–Oct · Jan–Feb",
  },
  {
    id: "namibia",
    name: "Namibia",
    latitude: -22.9576,
    longitude: 18.4904,
    zoom: 1.3,
    markerColor: GOLD_MARKER,
    flag: "🇳🇦",
    tagline: "Land of Endless Horizons",
    image: "/images/destinations/africa/namibia.webp",
    bestSeason: "May–Oct",
  },
  {
    id: "seychelles",
    name: "Seychelles",
    latitude: -4.6796,
    longitude: 55.492,
    zoom: 1.5,
    markerColor: GOLD_MARKER,
    flag: "🇸🇨",
    tagline: "Garden of the Indian Ocean",
    image: "/images/destinations/coastal/seychelles.webp",
    bestSeason: "Apr–May · Oct–Nov",
  },
  {
    id: "mauritius",
    name: "Mauritius",
    latitude: -20.3484,
    longitude: 57.5522,
    zoom: 1.48,
    markerColor: GOLD_MARKER,
    flag: "🇲🇺",
    tagline: "Star and Key of the Indian Ocean",
    image: "/images/destinations/coastal/mauritius.webp",
    bestSeason: "May–Dec",
  },
  {
    id: "oman",
    name: "Oman",
    latitude: 21.4735,
    longitude: 55.9754,
    zoom: 1.42,
    markerColor: GOLD_MARKER,
    flag: "🇴🇲",
    tagline: "Jewel of Arabia",
    image: "/images/destinations/uae/oman.webp",
    bestSeason: "Oct–Apr",
  },
  {
    id: "qatar",
    name: "Qatar",
    latitude: 25.3548,
    longitude: 51.1839,
    zoom: 1.5,
    markerColor: GOLD_MARKER,
    flag: "🇶🇦",
    tagline: "Where desert horizons meet contemporary luxury.",
    image: "/images/destinations/middle-east/qatar.jpg",
    bestSeason: "Nov–Mar",
  },
  {
    id: "peru",
    name: "Peru",
    latitude: -9.19,
    longitude: -75.0152,
    zoom: 1.3,
    markerColor: GOLD_MARKER,
    flag: "🇵🇪",
    tagline: "Land of the Incas",
    image: "/images/destinations/americas/peru.webp",
    bestSeason: "May–Sep",
  },
  {
    id: "chile",
    name: "Chile",
    latitude: -35.6751,
    longitude: -71.543,
    zoom: 1.28,
    markerColor: GOLD_MARKER,
    flag: "🇨🇱",
    tagline: "Land of Fire and Ice",
    image: "/images/destinations/americas/chile.webp",
    bestSeason: "Oct–Apr",
  },
  {
    id: "ecuador",
    name: "Ecuador",
    latitude: -1.8312,
    longitude: -78.1834,
    zoom: 1.34,
    markerColor: GOLD_MARKER,
    flag: "🇪🇨",
    tagline: "Middle of the World",
    image: "/images/destinations/americas/ecuador.webp",
    bestSeason: "Jun–Sep · Dec–Jan",
  },
  {
    id: "costa-rica",
    name: "Costa Rica",
    latitude: 9.7489,
    longitude: -83.7534,
    zoom: 1.38,
    markerColor: GOLD_MARKER,
    flag: "🇨🇷",
    tagline: "The Rich Coast",
    image: "/images/destinations/americas/costa-rica.webp",
    bestSeason: "Dec–Apr",
  },
  {
    id: "fiji",
    name: "Fiji",
    latitude: -17.7134,
    longitude: 178.065,
    zoom: 1.42,
    markerColor: GOLD_MARKER,
    flag: "🇫🇯",
    tagline: "Heart of the South Pacific",
    image: "/images/destinations/coastal/fiji.webp",
    bestSeason: "May–Oct",
  },
  {
    id: "french-polynesia",
    name: "French Polynesia",
    latitude: -17.6797,
    longitude: -149.4068,
    zoom: 1.4,
    markerColor: GOLD_MARKER,
    flag: "🇵🇫",
    tagline: "Islands of the Sacred Blue",
    image: "/images/destinations/coastal/french-polenisia.webp",
    bestSeason: "May–Oct",
  },
  {
    id: "saudi-arabia",
    name: "Saudi Arabia",
    latitude: 23.8859,
    longitude: 45.0792,
    zoom: 1.32,
    markerColor: GOLD_MARKER,
    flag: "🇸🇦",
    tagline: "Heart of Arabia",
    image: "/images/destinations/uae/saudi.webp",
    bestSeason: "Nov–Feb",
  }
]
