export interface Destination {
  id: string;
  name: string;
  tagline: string;
  latitude: number;
  longitude: number;
  zoom: number;
  markerColor: string;
  description: string;
  highlights: string[];
  bestSeason: string;
  flightTime: string;
  timeDifference: string;
  currency: string;
  flag: string;
  image: string;
}

const GOLD_MARKER = "#D4AF37";

export const destinations: Destination[] = [
  {
    id: "japan",
    name: "Japan",
    tagline: "Land of the Rising Sun",
    latitude: 36.2048,
    longitude: 138.2529,
    zoom: 1.34,
    markerColor: GOLD_MARKER,
    description:
      "Ancient temples, futuristic cities, refined cuisine and timeless rituals.",
    highlights: ["Tokyo", "Kyoto", "Mount Fuji"],
    bestSeason: "Mar–May · Oct–Nov",
    flightTime: "12h 30m",
    timeDifference: "3h 30m ahead of India",
    currency: "JPY",
    flag: "🇯🇵",
    image: "/images/destinations/japan.jpg",
  },
  {
    id: "switzerland",
    name: "Switzerland",
    tagline: "Home of the Alps",
    latitude: 46.8182,
    longitude: 8.2275,
    zoom: 1.4,
    markerColor: GOLD_MARKER,
    description:
      "Snow-covered peaks, lakeside towns and refined European journeys.",
    highlights: ["Zürich", "Zermatt", "Interlaken"],
    bestSeason: "May–Sep · Dec–Mar",
    flightTime: "14h 00m",
    timeDifference: "4h behind India",
    currency: "CHF",
    flag: "🇨🇭",
    image: "/images/destinations/switzerland.jpg",
  },
  {
    id: "france",
    name: "France",
    tagline: "Land of Art, Love & Light",
    latitude: 46.2276,
    longitude: 2.2137,
    zoom: 1.34,
    markerColor: GOLD_MARKER,
    description:
      "Iconic cities, refined cuisine, vineyard landscapes and timeless cultural heritage.",
    highlights: ["Paris", "French Riviera", "Provence"],
    bestSeason: "Apr–Jun · Sep–Oct",
    flightTime: "14h 00m",
    timeDifference: "5h behind India",
    currency: "EUR",
    flag: "🇫🇷",
    image: "/images/destinations/france.jpg",
  },
  {
    id: "italy",
    name: "Italy",
    tagline: "Cradle of the Renaissance",
    latitude: 42.8333,
    longitude: 12.8333,
    zoom: 1.34,
    markerColor: GOLD_MARKER,
    description:
      "Art, architecture, cuisine and landscapes shaped by centuries of beauty.",
    highlights: ["Rome", "Florence", "Amalfi Coast"],
    bestSeason: "Apr–Jun · Sep–Oct",
    flightTime: "13h 00m",
    timeDifference: "4h behind India",
    currency: "EUR",
    flag: "🇮🇹",
    image: "/images/destinations/italy.jpg",
  },
  {
    id: "germany",
    name: "Germany",
    tagline: "Land of Ideas and Castles",
    latitude: 51.1657,
    longitude: 10.4515,
    zoom: 1.34,
    markerColor: GOLD_MARKER,
    description:
      "Historic cities, forested landscapes, design culture and storybook towns.",
    highlights: ["Berlin", "Bavaria", "Rhine Valley"],
    bestSeason: "May–Sep",
    flightTime: "13h 00m",
    timeDifference: "4h behind India",
    currency: "EUR",
    flag: "🇩🇪",
    image: "/images/destinations/germany.jpg",
  },
  {
    id: "united-arab-emirates",
    name: "United Arab Emirates",
    tagline: "Where Vision Meets the Desert",
    latitude: 24.2075,
    longitude: 55.7447,
    zoom: 1.42,
    markerColor: GOLD_MARKER,
    description:
      "Bold architecture, desert landscapes and world-class Arabian hospitality.",
    highlights: ["Dubai", "Abu Dhabi", "Al Ain"],
    bestSeason: "Nov–Mar",
    flightTime: "4h 15m",
    timeDifference: "1h 30m behind India",
    currency: "AED",
    flag: "🇦🇪",
    image: "/images/destinations/united-arab-emirates.jpg",
  },
  {
    id: "maldives",
    name: "Maldives",
    tagline: "Jewels of the Indian Ocean",
    latitude: 3.2028,
    longitude: 73.2207,
    zoom: 1.5,
    markerColor: GOLD_MARKER,
    description: "Pristine atolls, overwater retreats and exceptional marine experiences.",
    highlights: ["Baa Atoll", "Ari Atoll", "North Malé Atoll"],
    bestSeason: "Nov–Apr",
    flightTime: "2h 10m",
    timeDifference: "30h behind India",
    currency: "MVR",
    flag: "🇲🇻",
    image: "/images/destinations/maldives.jpg",
  },
  {
    id: "singapore",
    name: "Singapore",
    tagline: "The Lion City",
    latitude: 1.3521,
    longitude: 103.8198,
    zoom: 1.46,
    markerColor: GOLD_MARKER,
    description:
      "A polished city-state where gardens, architecture and multicultural cuisine converge.",
    highlights: ["Marina Bay", "Gardens by the Bay", "Sentosa"],
    bestSeason: "Feb–Apr · Jul–Sep",
    flightTime: "4h 15m",
    timeDifference: "2h 30m ahead of India",
    currency: "SGD",
    flag: "🇸🇬",
    image: "/images/destinations/singapore.jpg",
  },
  {
    id: "greece",
    name: "Greece",
    tagline: "Birthplace of Gods and Legends",
    latitude: 39.0742,
    longitude: 21.8243,
    zoom: 1.38,
    markerColor: GOLD_MARKER,
    description:
      "Ancient landmarks, luminous islands and relaxed Mediterranean living.",
    highlights: ["Athens", "Santorini", "Crete"],
    bestSeason: "Apr–Jun · Sep–Oct",
    flightTime: "13h 00m",
    timeDifference: "3h behind India",
    currency: "EUR",
    flag: "🇬🇷",
    image: "/images/destinations/greece.jpg",
  },
  {
    id: "australia",
    name: "Australia",
    tagline: "The Land Down Under",
    latitude: -25.2744,
    longitude: 133.7751,
    zoom: 1.25,
    markerColor: GOLD_MARKER,
    description:
      "Cosmopolitan cities, ancient landscapes, remarkable wildlife and expansive coastlines.",
    highlights: ["Sydney", "Great Barrier Reef", "Uluru"],
    bestSeason: "Sep–Nov · Mar–May",
    flightTime: "15h 00m",
    timeDifference: "5h ahead of India",
    currency: "AUD",
    flag: "🇦🇺",
    image: "/images/destinations/australia.jpg",
  },
  {
    id: "new-zealand",
    name: "New Zealand",
    tagline: "Land of the Long White Cloud",
    latitude: -41.2,
    longitude: 174.0,
    zoom: 1.34,
    markerColor: GOLD_MARKER,
    description:
      "Cinematic mountains, pristine coastlines and deeply rooted Māori culture.",
    highlights: ["Auckland", "Queenstown", "Fiordland"],
    bestSeason: "Dec–Mar",
    flightTime: "20h 00m",
    timeDifference: "7h ahead of India",
    currency: "NZD",
    flag: "🇳🇿",
    image: "/images/destinations/new-zealand.jpg",
  },
  {
    id: "norway",
    name: "Norway",
    tagline: "Land of the Midnight Sun",
    latitude: 61.5,
    longitude: 9.0,
    zoom: 1.36,
    markerColor: GOLD_MARKER,
    description:
      "Deep fjords, sculpted mountains and immersive journeys into the Arctic north.",
    highlights: ["Oslo", "Norwegian Fjords", "Lofoten"],
    bestSeason: "May–Sep · Nov–Mar",
    flightTime: "15h 00m",
    timeDifference: "4h behind India",
    currency: "NOK",
    flag: "🇳🇴",
    image: "/images/destinations/norway.jpg",
  },
  {
    id: "iceland",
    name: "Iceland",
    tagline: "Land of Fire and Ice",
    latitude: 64.9631,
    longitude: -19.0208,
    zoom: 1.34,
    markerColor: GOLD_MARKER,
    description: "Glaciers, volcanoes, geothermal landscapes and elemental Nordic beauty.",
    highlights: ["Reykjavík", "South Coast", "Golden Circle"],
    bestSeason: "Jun–Aug · Sep–Mar",
    flightTime: "18h 30m",
    timeDifference: "5h 30m behind India",
    currency: "ISK",
    flag: "🇮🇸",
    image: "/images/destinations/iceland.jpg",
  },
  {
    id: "canada",
    name: "Canada",
    tagline: "The Great White North",
    latitude: 56.1304,
    longitude: -106.3468,
    zoom: 1.22,
    markerColor: GOLD_MARKER,
    description:
      "Vast wilderness, multicultural cities and extraordinary journeys from coast to coast.",
    highlights: ["Vancouver", "Canadian Rockies", "Québec"],
    bestSeason: "May–Sep · Dec–Mar",
    flightTime: "23h 00m",
    timeDifference: "11h 30m behind India",
    currency: "CAD",
    flag: "🇨🇦",
    image: "/images/destinations/canada.jpg",
  },
  {
    id: "united-kingdom",
    name: "United Kingdom",
    tagline: "Land of Royal Heritage",
    latitude: 54.0,
    longitude: -2.0,
    zoom: 1.34,
    markerColor: GOLD_MARKER,
    description:
      "Royal heritage, cosmopolitan culture and dramatic countryside across four nations.",
    highlights: ["London", "Scottish Highlands", "Cotswolds"],
    bestSeason: "May–Sep",
    flightTime: "14h 00m",
    timeDifference: "5h behind India",
    currency: "GBP",
    flag: "🇬🇧",
    image: "/images/destinations/united-kingdom.jpg",
  },
  {
    id: "spain",
    name: "Spain",
    tagline: "Land of Passion and Sun",
    latitude: 40.4637,
    longitude: -3.7492,
    zoom: 1.34,
    markerColor: GOLD_MARKER,
    description:
      "Expressive architecture, vibrant cities, Mediterranean coastlines and celebrated cuisine.",
    highlights: ["Madrid", "Barcelona", "Andalusia"],
    bestSeason: "Apr–Jun · Sep–Oct",
    flightTime: "15h 00m",
    timeDifference: "5h behind India",
    currency: "EUR",
    flag: "🇪🇸",
    image: "/images/destinations/spain.jpg",
  },
  {
    id: "turkiye",
    name: "Türkiye",
    tagline: "Where East Meets West",
    latitude: 38.9637,
    longitude: 35.2433,
    zoom: 1.34,
    markerColor: GOLD_MARKER,
    description:
      "Layered history, dramatic coastlines and remarkable cultural encounters.",
    highlights: ["Istanbul", "Cappadocia", "Bodrum"],
    bestSeason: "Apr–Jun · Sep–Oct",
    flightTime: "11h 00m",
    timeDifference: "2h 30m behind India",
    currency: "TRY",
    flag: "🇹🇷",
    image: "/images/destinations/turkiye.jpg",
  },
  {
    id: "austria",
    name: "Austria",
    tagline: "Land of Music and Mountains",
    latitude: 47.5162,
    longitude: 14.5501,
    zoom: 1.38,
    markerColor: GOLD_MARKER,
    description:
      "Imperial cities, classical culture and polished journeys through the Alps.",
    highlights: ["Vienna", "Salzburg", "Tyrol"],
    bestSeason: "May–Sep · Dec–Mar",
    flightTime: "13h 00m",
    timeDifference: "4h behind India",
    currency: "EUR",
    flag: "🇦🇹",
    image: "/images/destinations/austria.jpg",
  },
  {
    id: "portugal",
    name: "Portugal",
    tagline: "Land of Explorers",
    latitude: 39.3999,
    longitude: -8.2245,
    zoom: 1.38,
    markerColor: GOLD_MARKER,
    description:
      "Historic cities, Atlantic coastlines, vineyard valleys and soulful hospitality.",
    highlights: ["Lisbon", "Porto", "Algarve"],
    bestSeason: "Apr–Jun · Sep–Oct",
    flightTime: "16h 00m",
    timeDifference: "5h behind India",
    currency: "EUR",
    flag: "🇵🇹",
    image: "/images/destinations/portugal.jpg",
  },
  {
    id: "netherlands",
    name: "Netherlands",
    tagline: "Land of Canals and Masters",
    latitude: 52.1326,
    longitude: 5.2913,
    zoom: 1.4,
    markerColor: GOLD_MARKER,
    description:
      "Canal cities, contemporary design, open landscapes and rich artistic heritage.",
    highlights: ["Amsterdam", "Rotterdam", "Keukenhof"],
    bestSeason: "Apr–Sep",
    flightTime: "14h 00m",
    timeDifference: "4h behind India",
    currency: "EUR",
    flag: "🇳🇱",
    image: "/images/destinations/netherlands.jpg",
  },
  {
    id: "ireland",
    name: "Ireland",
    tagline: "The Emerald Isle",
    latitude: 53.1424,
    longitude: -7.6921,
    zoom: 1.4,
    markerColor: GOLD_MARKER,
    description:
      "Emerald landscapes, literary cities and warm journeys along the Atlantic edge.",
    highlights: ["Dublin", "Wild Atlantic Way", "Killarney"],
    bestSeason: "May–Sep",
    flightTime: "15h 00m",
    timeDifference: "5h behind India",
    currency: "EUR",
    flag: "🇮🇪",
    image: "/images/destinations/ireland.jpg",
  },
  {
    id: "belgium",
    name: "Belgium",
    tagline: "Heart of Europe",
    latitude: 50.5039,
    longitude: 4.4699,
    zoom: 1.42,
    markerColor: GOLD_MARKER,
    description:
      "Grand squares, medieval towns, culinary craft and distinctive European culture.",
    highlights: ["Brussels", "Bruges", "Antwerp"],
    bestSeason: "Apr–Sep",
    flightTime: "14h 00m",
    timeDifference: "4h behind India",
    currency: "EUR",
    flag: "🇧🇪",
    image: "/images/destinations/belgium.jpg",
  },
  {
    id: "denmark",
    name: "Denmark",
    tagline: "Land of Hygge",
    latitude: 56.2639,
    longitude: 9.5018,
    zoom: 1.42,
    markerColor: GOLD_MARKER,
    description:
      "Design-led cities, coastal landscapes and effortless Scandinavian living.",
    highlights: ["Copenhagen", "Aarhus", "North Zealand"],
    bestSeason: "May–Sep",
    flightTime: "14h 00m",
    timeDifference: "4h behind India",
    currency: "DKK",
    flag: "🇩🇰",
    image: "/images/destinations/denmark.jpg",
  },
  {
    id: "sweden",
    name: "Sweden",
    tagline: "Land of Forests and Light",
    latitude: 62.0,
    longitude: 15.0,
    zoom: 1.38,
    markerColor: GOLD_MARKER,
    description:
      "Elegant cities, vast forests, island archipelagos and northern light.",
    highlights: ["Stockholm", "Swedish Lapland", "Gothenburg"],
    bestSeason: "May–Sep · Dec–Mar",
    flightTime: "14h 30m",
    timeDifference: "4h behind India",
    currency: "SEK",
    flag: "🇸🇪",
    image: "/images/destinations/sweden.jpg",
  },
  {
    id: "czech-republic",
    name: "Czech Republic",
    tagline: "Heart of Bohemia",
    latitude: 49.8175,
    longitude: 15.473,
    zoom: 1.42,
    markerColor: GOLD_MARKER,
    description:
      "Gothic skylines, spa towns, castles and atmospheric Central European culture.",
    highlights: ["Prague", "Český Krumlov", "Karlovy Vary"],
    bestSeason: "Apr–Jun · Sep–Oct",
    flightTime: "13h 00m",
    timeDifference: "4h behind India",
    currency: "CZK",
    flag: "🇨🇿",
    image: "/images/destinations/czech-republic.jpg",
  },
  {
    id: "hungary",
    name: "Hungary",
    tagline: "Pearl of the Danube",
    latitude: 47.1625,
    longitude: 19.5033,
    zoom: 1.42,
    markerColor: GOLD_MARKER,
    description:
      "Monumental architecture, thermal traditions and rich culture along the Danube.",
    highlights: ["Budapest", "Lake Balaton", "Eger"],
    bestSeason: "Apr–Jun · Sep–Oct",
    flightTime: "13h 00m",
    timeDifference: "4h behind India",
    currency: "HUF",
    flag: "🇭🇺",
    image: "/images/destinations/hungary.jpg",
  },
  {
    id: "china",
    name: "China",
    tagline: "The Middle Kingdom",
    latitude: 35.8617,
    longitude: 104.1954,
    zoom: 1.28,
    markerColor: GOLD_MARKER,
    description:
      "Ancient wonders, dynamic megacities and extraordinary landscapes across a vast nation.",
    highlights: ["Beijing", "Shanghai", "Guilin"],
    bestSeason: "Apr–May · Sep–Oct",
    flightTime: "10h 30m",
    timeDifference: "2h 30m ahead of India",
    currency: "CNY",
    flag: "🇨🇳",
    image: "/images/destinations/china.jpg",
  },
  {
    id: "thailand",
    name: "Thailand",
    tagline: "Land of Smiles",
    latitude: 15.87,
    longitude: 100.9925,
    zoom: 1.36,
    markerColor: GOLD_MARKER,
    description: "Golden temples, tropical islands and vibrant street culture.",
    highlights: ["Bangkok", "Chiang Mai", "Phuket"],
    bestSeason: "Nov–Feb",
    flightTime: "5h 00m",
    timeDifference: "1h 30m ahead of India",
    currency: "THB",
    flag: "🇹🇭",
    image: "/images/destinations/thailand.jpg",
  },
  {
    id: "malaysia",
    name: "Malaysia",
    tagline: "Truly Asia",
    latitude: 4.2105,
    longitude: 101.9758,
    zoom: 1.4,
    markerColor: GOLD_MARKER,
    description:
      "Modern skylines, rainforest interiors, island retreats and multicultural cuisine.",
    highlights: ["Kuala Lumpur", "Langkawi", "Borneo"],
    bestSeason: "Mar–Sep",
    flightTime: "5h 00m",
    timeDifference: "2h 30m ahead of India",
    currency: "MYR",
    flag: "🇲🇾",
    image: "/images/destinations/malaysia.jpg",
  },
  {
    id: "south-korea",
    name: "South Korea",
    tagline: "Land of Morning Calm",
    latitude: 35.9078,
    longitude: 127.7669,
    zoom: 1.38,
    markerColor: GOLD_MARKER,
    description:
      "Royal heritage, contemporary design and energetic urban experiences.",
    highlights: ["Seoul", "Busan", "Jeju"],
    bestSeason: "Apr–Jun · Sep–Nov",
    flightTime: "12h 30m",
    timeDifference: "3h 30m ahead of India",
    currency: "KRW",
    flag: "🇰🇷",
    image: "/images/destinations/south-korea.jpg",
  },
  {
    id: "vietnam",
    name: "Vietnam",
    tagline: "Land of the Ascending Dragon",
    latitude: 14.0583,
    longitude: 108.2772,
    zoom: 1.38,
    markerColor: GOLD_MARKER,
    description:
      "Historic cities, dramatic landscapes and one of Asia’s richest culinary cultures.",
    highlights: ["Hanoi", "Ha Long Bay", "Hoi An"],
    bestSeason: "Feb–Apr · Aug–Oct",
    flightTime: "7h 30m",
    timeDifference: "1h 30m ahead of India",
    currency: "VND",
    flag: "🇻🇳",
    image: "/images/destinations/vietnam.jpg",
  },
  {
    id: "indonesia",
    name: "Indonesia",
    tagline: "Emerald of the Equator",
    latitude: -2.5489,
    longitude: 118.0149,
    zoom: 1.32,
    markerColor: GOLD_MARKER,
    description:
      "Volcanic islands, sacred traditions, tropical nature and extraordinary cultural diversity.",
    highlights: ["Bali", "Java", "Komodo"],
    bestSeason: "Apr–Oct",
    flightTime: "8h 30m",
    timeDifference: "2h 30m ahead of India",
    currency: "IDR",
    flag: "🇮🇩",
    image: "/images/destinations/indonesia.jpg",
  },
  {
    id: "philippines",
    name: "Philippines",
    tagline: "Pearl of the Orient Seas",
    latitude: 12.8797,
    longitude: 121.774,
    zoom: 1.38,
    markerColor: GOLD_MARKER,
    description:
      "Thousands of islands, turquoise waters, dramatic terraces and generous hospitality.",
    highlights: ["Manila", "Palawan", "Cebu"],
    bestSeason: "Dec–May",
    flightTime: "10h 30m",
    timeDifference: "2h 30m ahead of India",
    currency: "PHP",
    flag: "🇵🇭",
    image: "/images/destinations/philippines.jpg",
  },
  {
    id: "hong-kong",
    name: "Hong Kong",
    tagline: "Asia's World City",
    latitude: 22.3193,
    longitude: 114.1694,
    zoom: 1.5,
    markerColor: GOLD_MARKER,
    description:
      "A spectacular harbour city shaped by cuisine, culture, commerce and mountain scenery.",
    highlights: ["Victoria Harbour", "The Peak", "Lantau Island"],
    bestSeason: "Oct–Dec · Mar–Apr",
    flightTime: "9h 30m",
    timeDifference: "2h 30m ahead of India",
    currency: "HKD",
    flag: "🇭🇰",
    image: "/images/destinations/hong-kong.jpg",
  },
  {
    id: "united-states",
    name: "United States",
    tagline: "Land of Endless Possibility",
    latitude: 39.8283,
    longitude: -98.5795,
    zoom: 1.24,
    markerColor: GOLD_MARKER,
    description:
      "Iconic cities, national parks and diverse journeys across a continent-sized nation.",
    highlights: ["New York", "California", "National Parks"],
    bestSeason: "Apr–Jun · Sep–Oct",
    flightTime: "23h 00m",
    timeDifference: "11h 30m behind India",
    currency: "USD",
    flag: "🇺🇸",
    image: "/images/destinations/united-states.jpg",
  },
  {
    id: "mexico",
    name: "Mexico",
    tagline: "Land of Sun and Soul",
    latitude: 23.6345,
    longitude: -102.5528,
    zoom: 1.3,
    markerColor: GOLD_MARKER,
    description:
      "Ancient civilisations, expressive cuisine, colonial cities and Caribbean shores.",
    highlights: ["Mexico City", "Yucatán", "Los Cabos"],
    bestSeason: "Nov–Apr",
    flightTime: "24h 30m",
    timeDifference: "12h 30m behind India",
    currency: "MXN",
    flag: "🇲🇽",
    image: "/images/destinations/mexico.jpg",
  },
  {
    id: "egypt",
    name: "Egypt",
    tagline: "Gift of the Nile",
    latitude: 26.8206,
    longitude: 30.8025,
    zoom: 1.32,
    markerColor: GOLD_MARKER,
    description:
      "Ancient wonders, Nile journeys and timeless desert landscapes.",
    highlights: ["Cairo", "Luxor", "Aswan"],
    bestSeason: "Oct–Apr",
    flightTime: "11h 30m",
    timeDifference: "3h behind India",
    currency: "EGP",
    flag: "🇪🇬",
    image: "/images/destinations/egypt.jpg",
  },
  {
    id: "south-africa",
    name: "South Africa",
    tagline: "A World in One Country",
    latitude: -30.5595,
    longitude: 22.9375,
    zoom: 1.3,
    markerColor: GOLD_MARKER,
    description:
      "Wildlife, wine country, dramatic coastlines and vibrant urban culture.",
    highlights: ["Cape Town", "Kruger National Park", "Winelands"],
    bestSeason: "Mar–May · Sep–Nov",
    flightTime: "14h 30m",
    timeDifference: "3h 30m behind India",
    currency: "ZAR",
    flag: "🇿🇦",
    image: "/images/destinations/south-africa.jpg",
  },
  {
    id: "brazil",
    name: "Brazil",
    tagline: "Land of Rhythm and Rainforest",
    latitude: -14.235,
    longitude: -51.9253,
    zoom: 1.26,
    markerColor: GOLD_MARKER,
    description:
      "Immense nature, energetic cities, iconic coastlines and rich cultural expression.",
    highlights: ["Rio de Janeiro", "Amazon", "Iguaçu Falls"],
    bestSeason: "May–Sep",
    flightTime: "25h 00m",
    timeDifference: "8h 30m behind India",
    currency: "BRL",
    flag: "🇧🇷",
    image: "/images/destinations/brazil.jpg",
  },
  {
    id: "argentina",
    name: "Argentina",
    tagline: "Land of Silver and Passion",
    latitude: -38.4161,
    longitude: -63.6167,
    zoom: 1.28,
    markerColor: GOLD_MARKER,
    description:
      "Cosmopolitan culture, Patagonian wilderness, wine country and dramatic southern landscapes.",
    highlights: ["Buenos Aires", "Patagonia", "Mendoza"],
    bestSeason: "Oct–Apr",
    flightTime: "27h 00m",
    timeDifference: "8h 30m behind India",
    currency: "ARS",
    flag: "🇦🇷",
    image: "/images/destinations/argentina.jpg",
  },
  {
    id: "india",
    name: "India",
    tagline: "A World Within One Nation",
    latitude: 20.5937,
    longitude: 78.9629,
    zoom: 1.26,
    markerColor: GOLD_MARKER,
    description: "Layered heritage, extraordinary cuisine, spiritual traditions and landscapes of remarkable contrast.",
    highlights: ["Rajasthan", "Kerala", "Himalayas"],
    bestSeason: "Oct–Mar",
    flightTime: "3h 30m",
    timeDifference: "Same time as India",
    currency: "INR",
    flag: "🇮🇳",
    image: "/images/destinations/india.jpg",
  },
  {
    id: "sri-lanka",
    name: "Sri Lanka",
    tagline: "Pearl of the Indian Ocean",
    latitude: 7.8731,
    longitude: 80.7718,
    zoom: 1.42,
    markerColor: GOLD_MARKER,
    description: "Tea country, ancient cities, wildlife reserves and elegant Indian Ocean coastlines.",
    highlights: ["Sigiriya", "Ella", "Galle"],
    bestSeason: "Dec–Mar · Jul–Sep",
    flightTime: "1h 25m",
    timeDifference: "Same time as India",
    currency: "LKR",
    flag: "🇱🇰",
    image: "/images/destinations/sri-lanka.jpg",
  },
  {
    id: "nepal",
    name: "Nepal",
    tagline: "Roof of the World",
    latitude: 28.3949,
    longitude: 84.124,
    zoom: 1.42,
    markerColor: GOLD_MARKER,
    description: "Himalayan landscapes, sacred heritage and deeply immersive mountain journeys.",
    highlights: ["Kathmandu", "Everest Region", "Pokhara"],
    bestSeason: "Oct–Nov · Mar–Apr",
    flightTime: "6h 00m",
    timeDifference: "15h ahead of India",
    currency: "NPR",
    flag: "🇳🇵",
    image: "/images/destinations/nepal.jpg",
  },
  {
    id: "bhutan",
    name: "Bhutan",
    tagline: "The Last Shangri-La",
    latitude: 27.5142,
    longitude: 90.4336,
    zoom: 1.44,
    markerColor: GOLD_MARKER,
    description: "Cliffside monasteries, pristine valleys and a rare philosophy of mindful travel.",
    highlights: ["Paro", "Thimphu", "Punakha"],
    bestSeason: "Mar–May · Sep–Nov",
    flightTime: "8h 30m",
    timeDifference: "30h ahead of India",
    currency: "BTN",
    flag: "🇧🇹",
    image: "/images/destinations/bhutan.jpg",
  },
  {
    id: "cambodia",
    name: "Cambodia",
    tagline: "Kingdom of Wonder",
    latitude: 12.5657,
    longitude: 104.991,
    zoom: 1.42,
    markerColor: GOLD_MARKER,
    description: "Monumental Khmer heritage, river landscapes and a quietly evolving cultural scene.",
    highlights: ["Angkor", "Phnom Penh", "Tonlé Sap"],
    bestSeason: "Nov–Feb",
    flightTime: "8h 30m",
    timeDifference: "1h 30m ahead of India",
    currency: "KHR",
    flag: "🇰🇭",
    image: "/images/destinations/cambodia.jpg",
  },
  {
    id: "taiwan",
    name: "Taiwan",
    tagline: "The Beautiful Island",
    latitude: 23.6978,
    longitude: 120.9605,
    zoom: 1.46,
    markerColor: GOLD_MARKER,
    description: "Mountain scenery, dynamic cities, night markets and refined island culture.",
    highlights: ["Taipei", "Taroko Gorge", "Sun Moon Lake"],
    bestSeason: "Oct–Apr",
    flightTime: "10h 30m",
    timeDifference: "2h 30m ahead of India",
    currency: "TWD",
    flag: "🇹🇼",
    image: "/images/destinations/taiwan.jpg",
  },
  {
    id: "uzbekistan",
    name: "Uzbekistan",
    tagline: "Heart of the Silk Road",
    latitude: 41.3775,
    longitude: 64.5853,
    zoom: 1.36,
    markerColor: GOLD_MARKER,
    description: "Blue-tiled cities, desert history and the architectural splendour of the Silk Road.",
    highlights: ["Samarkand", "Bukhara", "Khiva"],
    bestSeason: "Apr–May · Sep–Oct",
    flightTime: "11h 30m",
    timeDifference: "30h behind India",
    currency: "UZS",
    flag: "🇺🇿",
    image: "/images/destinations/uzbekistan.jpg",
  },
  {
    id: "georgia",
    name: "Georgia",
    tagline: "Balcony of Europe",
    latitude: 42.3154,
    longitude: 43.3569,
    zoom: 1.4,
    markerColor: GOLD_MARKER,
    description: "Caucasus mountains, ancient wine culture and expressive hospitality.",
    highlights: ["Tbilisi", "Kazbegi", "Kakheti"],
    bestSeason: "May–Jun · Sep–Oct",
    flightTime: "11h 30m",
    timeDifference: "1h 30m behind India",
    currency: "GEL",
    flag: "🇬🇪",
    image: "/images/destinations/georgia.jpg",
  },
  {
    id: "finland",
    name: "Finland",
    tagline: "Land of a Thousand Lakes",
    latitude: 61.9241,
    longitude: 25.7482,
    zoom: 1.38,
    markerColor: GOLD_MARKER,
    description: "Design-led cities, forest retreats, lake country and Arctic winter experiences.",
    highlights: ["Helsinki", "Finnish Lapland", "Lakeland"],
    bestSeason: "Jun–Aug · Dec–Mar",
    flightTime: "15h 30m",
    timeDifference: "3h behind India",
    currency: "EUR",
    flag: "🇫🇮",
    image: "/images/destinations/finland.jpg",
  },
  {
    id: "croatia",
    name: "Croatia",
    tagline: "Pearl of the Adriatic",
    latitude: 45.1,
    longitude: 15.2,
    zoom: 1.4,
    markerColor: GOLD_MARKER,
    description: "Historic coastal cities, clear Adriatic waters and elegant island journeys.",
    highlights: ["Dubrovnik", "Split", "Hvar"],
    bestSeason: "May–Jun · Sep",
    flightTime: "14h 30m",
    timeDifference: "4h behind India",
    currency: "EUR",
    flag: "🇭🇷",
    image: "/images/destinations/croatia.jpg",
  },
  {
    id: "poland",
    name: "Poland",
    tagline: "Land of Resilience and Heritage",
    latitude: 51.9194,
    longitude: 19.1451,
    zoom: 1.38,
    markerColor: GOLD_MARKER,
    description: "Restored cities, cultural depth, forest landscapes and compelling modern energy.",
    highlights: ["Warsaw", "Kraków", "Gdańsk"],
    bestSeason: "May–Sep",
    flightTime: "14h 00m",
    timeDifference: "4h behind India",
    currency: "PLN",
    flag: "🇵🇱",
    image: "/images/destinations/poland.jpg",
  },
  {
    id: "morocco",
    name: "Morocco",
    tagline: "Gateway to Africa",
    latitude: 31.7917,
    longitude: -7.0926,
    zoom: 1.34,
    markerColor: GOLD_MARKER,
    description: "Medinas, desert camps, mountain retreats and richly layered design traditions.",
    highlights: ["Marrakech", "Fès", "Sahara"],
    bestSeason: "Mar–May · Sep–Nov",
    flightTime: "15h 30m",
    timeDifference: "5h behind India",
    currency: "MAD",
    flag: "🇲🇦",
    image: "/images/destinations/morocco.jpg",
  },
  {
    id: "kenya",
    name: "Kenya",
    tagline: "Home of the Great Safari",
    latitude: -0.0236,
    longitude: 37.9062,
    zoom: 1.32,
    markerColor: GOLD_MARKER,
    description: "Iconic wildlife, sweeping savannahs and refined journeys through East Africa.",
    highlights: ["Maasai Mara", "Amboseli", "Laikipia"],
    bestSeason: "Jul–Oct · Jan–Feb",
    flightTime: "11h 30m",
    timeDifference: "2h 30m behind India",
    currency: "KES",
    flag: "🇰🇪",
    image: "/images/destinations/kenya.jpg",
  },
  {
    id: "tanzania",
    name: "Tanzania",
    tagline: "Soul of the Serengeti",
    latitude: -6.369,
    longitude: 34.8888,
    zoom: 1.32,
    markerColor: GOLD_MARKER,
    description: "Legendary safari landscapes, Kilimanjaro and the turquoise shores of Zanzibar.",
    highlights: ["Serengeti", "Ngorongoro", "Zanzibar"],
    bestSeason: "Jun–Oct · Jan–Feb",
    flightTime: "12h 30m",
    timeDifference: "2h 30m behind India",
    currency: "TZS",
    flag: "🇹🇿",
    image: "/images/destinations/tanzania.jpg",
  },
  {
    id: "namibia",
    name: "Namibia",
    tagline: "Land of Endless Horizons",
    latitude: -22.9576,
    longitude: 18.4904,
    zoom: 1.3,
    markerColor: GOLD_MARKER,
    description: "Sculpted dunes, remote wilderness and dramatic journeys through southern Africa.",
    highlights: ["Sossusvlei", "Etosha", "Skeleton Coast"],
    bestSeason: "May–Oct",
    flightTime: "16h 30m",
    timeDifference: "3h 30m behind India",
    currency: "NAD",
    flag: "🇳🇦",
    image: "/images/destinations/namibia.jpg",
  },
  {
    id: "seychelles",
    name: "Seychelles",
    tagline: "Garden of the Indian Ocean",
    latitude: -4.6796,
    longitude: 55.492,
    zoom: 1.5,
    markerColor: GOLD_MARKER,
    description: "Granite islands, secluded beaches and luxurious tropical seclusion.",
    highlights: ["Mahé", "Praslin", "La Digue"],
    bestSeason: "Apr–May · Oct–Nov",
    flightTime: "8h 30m",
    timeDifference: "1h 30m behind India",
    currency: "SCR",
    flag: "🇸🇨",
    image: "/images/destinations/seychelles.jpg",
  },
  {
    id: "mauritius",
    name: "Mauritius",
    tagline: "Star and Key of the Indian Ocean",
    latitude: -20.3484,
    longitude: 57.5522,
    zoom: 1.48,
    markerColor: GOLD_MARKER,
    description: "Lagoon resorts, volcanic scenery and a distinctive multicultural island identity.",
    highlights: ["Le Morne", "Chamarel", "Grand Baie"],
    bestSeason: "May–Dec",
    flightTime: "8h 30m",
    timeDifference: "1h 30m behind India",
    currency: "MUR",
    flag: "🇲🇺",
    image: "/images/destinations/mauritius.jpg",
  },
  {
    id: "oman",
    name: "Oman",
    tagline: "Jewel of Arabia",
    latitude: 21.4735,
    longitude: 55.9754,
    zoom: 1.42,
    markerColor: GOLD_MARKER,
    description: "Mountain roads, desert camps, ancient forts and understated Arabian hospitality.",
    highlights: ["Muscat", "Nizwa", "Wahiba Sands"],
    bestSeason: "Oct–Apr",
    flightTime: "6h 00m",
    timeDifference: "1h 30m behind India",
    currency: "OMR",
    flag: "🇴🇲",
    image: "/images/destinations/oman.jpg",
  },
  {
    id: "qatar",
    name: "Qatar",
    tagline: "The Pearl of the Gulf",
    latitude: 25.3548,
    longitude: 51.1839,
    zoom: 1.45,
    markerColor: GOLD_MARKER,
    description: "Contemporary architecture, cultural institutions and polished desert experiences.",
    highlights: ["Doha", "Museum of Islamic Art", "Inland Sea"],
    bestSeason: "Nov–Mar",
    flightTime: "6h 00m",
    timeDifference: "2h 30m behind India",
    currency: "QAR",
    flag: "🇶🇦",
    image: "/images/destinations/qatar.jpg",
  },
  {
    id: "peru",
    name: "Peru",
    tagline: "Land of the Incas",
    latitude: -9.19,
    longitude: -75.0152,
    zoom: 1.3,
    markerColor: GOLD_MARKER,
    description: "Inca heritage, dramatic Andean landscapes and one of the world’s great cuisines.",
    highlights: ["Machu Picchu", "Cusco", "Sacred Valley"],
    bestSeason: "May–Sep",
    flightTime: "27h 00m",
    timeDifference: "10h 30m behind India",
    currency: "PEN",
    flag: "🇵🇪",
    image: "/images/destinations/peru.jpg",
  },
  {
    id: "chile",
    name: "Chile",
    tagline: "Land of Fire and Ice",
    latitude: -35.6751,
    longitude: -71.543,
    zoom: 1.28,
    markerColor: GOLD_MARKER,
    description: "Atacama skies, wine valleys, Pacific cities and the wilderness of Patagonia.",
    highlights: ["Atacama", "Santiago", "Torres del Paine"],
    bestSeason: "Oct–Apr",
    flightTime: "28h 00m",
    timeDifference: "9h behind India",
    currency: "CLP",
    flag: "🇨🇱",
    image: "/images/destinations/chile.jpg",
  },
  {
    id: "ecuador",
    name: "Ecuador",
    tagline: "Middle of the World",
    latitude: -1.8312,
    longitude: -78.1834,
    zoom: 1.34,
    markerColor: GOLD_MARKER,
    description: "Andean cities, cloud forests, Pacific shores and the Galápagos Islands.",
    highlights: ["Quito", "Galápagos", "Cuenca"],
    bestSeason: "Jun–Sep · Dec–Jan",
    flightTime: "27h 00m",
    timeDifference: "10h 30m behind India",
    currency: "USD",
    flag: "🇪🇨",
    image: "/images/destinations/ecuador.jpg",
  },
  {
    id: "costa-rica",
    name: "Costa Rica",
    tagline: "The Rich Coast",
    latitude: 9.7489,
    longitude: -83.7534,
    zoom: 1.38,
    markerColor: GOLD_MARKER,
    description: "Rainforests, volcanoes, wildlife and eco-luxury between two oceans.",
    highlights: ["Arenal", "Monteverde", "Osa Peninsula"],
    bestSeason: "Dec–Apr",
    flightTime: "26h 00m",
    timeDifference: "11h 30m behind India",
    currency: "CRC",
    flag: "🇨🇷",
    image: "/images/destinations/costa-rica.jpg",
  },
  {
    id: "fiji",
    name: "Fiji",
    tagline: "Heart of the South Pacific",
    latitude: -17.7134,
    longitude: 178.065,
    zoom: 1.42,
    markerColor: GOLD_MARKER,
    description: "Private islands, coral reefs and warm South Pacific hospitality.",
    highlights: ["Mamanuca Islands", "Yasawa Islands", "Vanua Levu"],
    bestSeason: "May–Oct",
    flightTime: "22h 30m",
    timeDifference: "6h 30m ahead of India",
    currency: "FJD",
    flag: "🇫🇯",
    image: "/images/destinations/fiji.jpg",
  },
  {
    id: "french-polynesia",
    name: "French Polynesia",
    tagline: "Islands of the Sacred Blue",
    latitude: -17.6797,
    longitude: -149.4068,
    zoom: 1.4,
    markerColor: GOLD_MARKER,
    description: "Volcanic islands, luminous lagoons and some of the Pacific’s most exclusive retreats.",
    highlights: ["Bora Bora", "Tahiti", "Moorea"],
    bestSeason: "May–Oct",
    flightTime: "29h 00m",
    timeDifference: "15h 30m behind India",
    currency: "XPF",
    flag: "🇵🇫",
    image: "/images/destinations/french-polynesia.jpg",
  },
  {
    id: "saudi-arabia",
    name: "Saudi Arabia",
    tagline: "Heart of Arabia",
    latitude: 23.8859,
    longitude: 45.0792,
    zoom: 1.32,
    markerColor: GOLD_MARKER,
    description: "Ancient trade routes, desert landscapes and ambitious new cultural destinations.",
    highlights: ["AlUla", "Riyadh", "Jeddah"],
    bestSeason: "Nov–Feb",
    flightTime: "7h 30m",
    timeDifference: "2h 30m behind India",
    currency: "SAR",
    flag: "🇸🇦",
    image: "/images/destinations/saudi-arabia.jpg",
  },
]
